[libraries]

osvvm.files = [
  '.venv/lib/python3.11/site-packages/vunit/vhdl/osvvm/*.vhd',
]

spi_lib.files = [
  'src/spi_master.vhd',
  'src/spi_package.vhd',
  'src/simulation/tb_spi_master.vhd',
  'src/simulation/tb_package.vhd',
]

vunit_lib.files = [
  '.venv/lib/python3.11/site-packages/vunit/vhdl/*.vhd',
  '.venv/lib/python3.11/site-packages/vunit/vhdl/*/src/*.vhd',
]

